import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import usePosts from '../hooks/usePosts'
import useFilter from '../hooks/useFilter'
import axios from 'axios'

export default function Home() {

  const [posts, setPosts] = useState([])
  const { Posts } = usePosts(posts)
  const { FiltroUI } = useFilter()

  useEffect(() => {
    const obterPosts = async () => {
      const resultado = await axios.get('http://localhost:1337/posts')
      setPosts(resultado.data);
      //console.log(resultado.data);
    }
    obterPosts()
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          Blog<a href="https://nextjs.org">CAPO Viagens</a>
        </h1>

        <p className={styles.description}>
          Postagens{' '}
          <code className={styles.code}> legais</code>
        </p>
        <p className={styles.description}>
          <FiltroUI />
        </p>
        <div className={styles.grid}>
          <Posts />
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
