import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import products from '../../products.json'
import { fromImageToUrl } from '../../utils/urls'
import axios from 'axios'

export default function Home() {


  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          <a href="https://nextjs.org">Produtos</a>
        </h1>

        <p className={styles.description}>
          Produtos{' '}
          <code className={styles.code}> legais</code>
        </p>
        <div className={styles.grid}>
          {products.map(product => (
            <div className={styles.card}>
              <div>{product.nome}</div>
              <div><img src={fromImageToUrl(product.foto)} width={200} height={200} /></div>
              {/* <div>{product.descricao}</div> */}
              <div>{product.preco}</div>
            </div>
          ))}
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
