import { useEffect, useState } from 'react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import styles from '../../styles/Home.module.css'
import { fromImageToUrl, API_URL } from '../../utils/urls'
import { twoDecimals } from '../../utils/format'
import axios from 'axios'

export default function Produtos({ produtos }) {

  console.log(produtos);


  return (
    <div className={styles.container}>
      <Head>
        <title>Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>

        <h1 className={styles.title}>
          <a href="https://nextjs.org">Produtos</a>
        </h1>

        <p className={styles.description}>
          Produtos{' '}
          <code className={styles.code}> legais</code>
        </p>
        <div className={styles.grid} style={{ width: "650px" }}>
          {produtos.map(produto => (
            <Link href={`/produtos/${produto.slug}`}>
              <a className={styles.card} key={produto.slug}>
                <div><h4 style={{ textAlign: "justify" }}>{produto.nome}</h4></div>
                <div style={{ padding: " 20px 0", textAlign: "center" }} ><img src={fromImageToUrl(produto.foto)} width={200} height={200} /></div>
                {/* <div>{produto.descricao}</div> */}
                <div style={{ textAlign: "left" }}><h4>R$: {twoDecimals(produto.preco)}</h4></div>
              </a>
            </Link>
          ))}
        </div>

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}

export async function getStaticProps() {
  const { data: produtos } = await axios.get(
    `${API_URL}/produtos`);
  return { props: { produtos } };
}